name: Build Application and Make Release

on:
  push:
    tags:
      - '*'

jobs:

  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    with:
      build_type: Release
      is_qt_cached: false
    secrets:
      SPARKLE_ED25519_KEY: ${{ secrets.SPARKLE_ED25519_KEY }}

  create_release:
    needs: build_release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          path: 'PrismLauncher-source'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/PrismLauncher-source PrismLauncher-${{ env.VERSION }}
          mv PrismLauncher-Linux-Qt6-Portable*/PrismLauncher-portable.tar.gz PrismLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-Linux-Qt6*/PrismLauncher.tar.gz PrismLauncher-Linux-Qt6-${{ env.VERSION }}.tar.gz          
          mv PrismLauncher-Linux-Portable*/PrismLauncher-portable.tar.gz PrismLauncher-Linux-Portable-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-Linux*/PrismLauncher.tar.gz PrismLauncher-Linux-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-*.AppImage/PrismLauncher-*.AppImage PrismLauncher-Linux-${{ env.VERSION }}-x86_64.AppImage
          mv PrismLauncher-macOS-Legacy*/PrismLauncher.tar.gz PrismLauncher-macOS-Legacy-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-macOS*/PrismLauncher.tar.gz PrismLauncher-macOS-${{ env.VERSION }}.tar.gz
          mv PrismLauncher-Windows-MinGW-w64-Legacy-Portable* PrismLauncher-Windows-MinGW-w64-Legacy-Portable-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MinGW-w64-Legacy-Setup*/PrismLauncher-Setup.exe PrismLauncher-Windows-MinGW-w64-Legacy-Setup-${{ env.VERSION }}.exe
          mv PrismLauncher-Windows-MinGW-w64-Legacy* PrismLauncher-Windows-MinGW-w64-Legacy-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MinGW-w64-Portable* PrismLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MinGW-w64-Setup*/PrismLauncher-Setup.exe PrismLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
          mv PrismLauncher-Windows-MinGW-w64* PrismLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-Legacy-Portable* PrismLauncher-Windows-MSVC-Legacy-Portable-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-Legacy-Setup*/PrismLauncher-Setup.exe PrismLauncher-Windows-MSVC-Legacy-Setup-${{ env.VERSION }}.exe
          mv PrismLauncher-Windows-MSVC-Legacy* PrismLauncher-Windows-MSVC-Legacy-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-arm64-Portable* PrismLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-arm64-Setup*/PrismLauncher-Setup.exe PrismLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
          mv PrismLauncher-Windows-MSVC-arm64* PrismLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-Portable* PrismLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
          mv PrismLauncher-Windows-MSVC-Setup*/PrismLauncher-Setup.exe PrismLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
          mv PrismLauncher-Windows-MSVC* PrismLauncher-Windows-MSVC-${{ env.VERSION }}.zip

          tar -czf PrismLauncher-${{ env.VERSION }}.tar.gz PrismLauncher-${{ env.VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Prism Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          files: |
            PrismLauncher-Linux-${{ env.VERSION }}.tar.gz
            PrismLauncher-Linux-Portable-${{ env.VERSION }}.tar.gz
            PrismLauncher-Linux-${{ env.VERSION }}-x86_64.AppImage
            PrismLauncher-Linux-Qt6-${{ env.VERSION }}.tar.gz
            PrismLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            PrismLauncher-Windows-MinGW-Legacy-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MinGW-Legacy-Portable-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MinGW-Legacy-Setup-${{ env.VERSION }}.exe
            PrismLauncher-Windows-MinGW-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MinGW-Portable-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MinGW-Setup-${{ env.VERSION }}.exe
            PrismLauncher-Windows-MSVC-Legacy-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Legacy-Portable-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Legacy-Setup-${{ env.VERSION }}.exe
            PrismLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            PrismLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            PrismLauncher-macOS-${{ env.VERSION }}.tar.gz
            PrismLauncher-macOS-Legacy-${{ env.VERSION }}.tar.gz
            PrismLauncher-${{ env.VERSION }}.tar.gz
